<?php 
session_start(); 
include 'send.php';
?>
﻿<head>
    <script src="jquery.js" type="text/javascript"></script>
    <script>
        $(function(){
            var i = 0;			//счетчик комнат
            $('#ch1').on('change', function(){
                //console.dir("#rooms");
                $('#rooms').removeAttr('hidden');
                //console.log($('#ch1').val());

            });
            $('.room').on('change', function(){
                if($(this).prop("checked")) {
                    if ($('#ch1').val() > i){
        //console.dir($(this));
                        $('#rooms').append("<label class='" + $(this).prop('id') + "'>Введите квадратуру " + $(this).prop('defaultValue') + ":</label>");
                        $('#rooms').append("<input type='text' name='" + $(this).prop('defaultValue') + "' pattern='[0-9]{1,3}(\.[0-9]+)?' required class='" + $(this).prop('id') + "'><br>");
                        //$('#rooms').append("<input type='hidden' name='name' value='" + $(this).prop('defaultValue') + "'>");
                        i++;
                        //console.log($('#ch1').val(), i);
                        if ($('#ch1').val() == i){
                            $("input[type=checkbox]").each(function() {
                                    if(!$(this).prop('checked')) $(this).prop('disabled','true');
                                    $("#but1").removeAttr('disabled');
                            });
                        }
                    }					
                }else{
                    $("." + $(this).prop('id')).remove();
                    $("input[type=checkbox]").each(function() {							
                        if(!$(this).prop('checked')) {
                            $(this).removeAttr('disabled');
                            $("#but1").prop('disabled','true');
                        }
                    });
                    i--;
                } 
                //console.dir($(this));
                //console.dir($(this).prop("defaultValue"));
            });
            $('#form2').submit(function(){
                
                $.ajax({
                    type: "POST",
                    url: "send.php", 
                    data: $(this).serialize(),
                    success: function() {
                       
                       alert("Ваше сообщение отпрвлено!");
                    }
                });
                $("#but2").prop('disabled','true');
                return false;
            });
        });
    </script>
</head>
<form method="post" action="<?php $_SERVER['PHP_SELF'] ?>" id="f1">
	<label for="znak">Выберите тип кондиционера</label>
	<select name="znak" id="znak">
		<option value="0">Охлаждение</option>
		<option value="1">Нагрев</option>
		<option value="2">Охлаждение/Нагрев</option>
	</select><br>
	<label for="ch1">Введите количество комнат:</label>
	<input type="number" name="room" id="ch1" required min="1" max="5"><br>
	<fieldset hidden id="rooms">
		<label for="zal">Зал</label>
		<input type="checkbox"  id="zal" class="room" value="зала"><br>
		<label for="k">Кухня</label>
		<input type="checkbox" id="k" class="room" value="кухни"><br>
		<label for="1sp">1-я спальня</label>
		<input type="checkbox" id="1sp" class="room" value="1-й спальни"><br>
		<label for="2sp">2-я спальня</label>
		<input type="checkbox" id="2sp" class="room" value="2-й спальни"><br>
		<label for="3sp">3-я спальня</label>
		<input type="checkbox" id="3sp" class="room" value="3-й спальни"><br>
	</fieldset>
	<input type="submit" value="Вычислить" id="but1" disabled>
</form>

<?php

	if ($_SERVER["REQUEST_METHOD"] == "POST"){
            
//echo "<pre>";
//var_dump($_POST);
//echo "</pre>";
             
            if(isset($_POST["email"])){
//                if (mail($_POST["email"], "Заказ на кондиционеры", $_SESSION["mes"]))
//                    echo "<br>Почта успешно отправлена!";
//                else echo "<br>произошла ошибка при отправке почты!";
            }else{
                switch($_POST["znak"]){
                        case '0': $k = 280; $tip = "Охлаждение"; break;
                        case '1': $k = 400; $tip = "Нагрев"; break;
                        case '2': $k = 350; $tip = "Охлаждение/Нагрев"; break;
		}
		$i = 0;     //счётчик комнат
                $btu = array();
                $message =  "<p>Вы выбрали тип кондиционера \"$tip\"</p><p>для {$_POST["room"]} комнат</p>";
                foreach($_POST as $key=>$v){
                    
                    if($key != znak && $key != room){
                        $btu[] = ceil($v*$k);
                        if($btu[$i] <= 7000){
                            $message .= "Вам нужен кондиционер на 7000 BTU<br>";
                        }elseif ($btu[$i] > 7000 && $bpu <= 9000){
                            $message .= "Вам нужен кондиционер на 9000 BTU<br>";
                        }elseif ($btu[$i] > 9000 && $bpu <= 12000){
                            $message .=  "Вам нужен кондиционер на 12000 BTU<br>";
                        }elseif ($btu[$i] > 12000 && $bpu <= 18000){
                            $message .=  "Вам нужен кондиционер на 18000 BTU<br>";
                        }elseif ($btu[$i] > 12000 && $bpu <= 24000){
                            $message .=  "Вам нужен кондиционер на 24000 BTU<br>";
                        }else echo "Вам нужен кондиционер мощнее 24000 BTU<br>";

                        $message .=  "для $key ".$_POST[$key]." кв.м.<br>";
                        
                        $i++;
                    }
                    
                }
                $_SESSION["mes"] = $message;
                echo $message;
                require 'zakaz.html';
            }       
		
	}
?>
